# Python

In [15]:
x = 3
y = 5.2  #float
a = "a simple test" #a str
b = False  #bool
print(type(y), type(a), type(b))

<class 'float'> <class 'str'> <class 'bool'>


simple string operations

In [12]:
a
print(a[0])
print(a[0:7])
print(a[:7])
print(a*3)
print(a + "Hello")
print(a.upper())
print(a.replace("i", "II"))

a
a simpl
a simpl
a simple testa simple testa simple test
a simple testHello
A SIMPLE TEST
a sIImple test


In [16]:
# comparison
print(4 < 3)
x == y

False


False

## Lists, Tuples, Dictionary

In [21]:
a_list = [4, 2, "hello", 5.2]
a_list[2]
a_list[:2]
a_list[-1]
a_list.append(42)
a_list

[4, 2, 'hello', 5.2, 42]

In [23]:
other_list = [[1,9], [2,4,0], [3, 4]]
other_list[1][0]

2

In [25]:
a_tuple = (4, 6, "hello")
a_tuple

(4, 6, 'hello')

In [27]:
a_dictionary = {"data science": "fun", "math": "beautiful", "computer science": 42}
a_dictionary
a_dictionary["math"]

'beautiful'

## if-else and loops 

In [29]:
name = "Alice"
if name == "Alice":
    print("Hi Alice")
else:
    print("not Alice")
print("continue")


Hi Alice
continue


In [30]:
for i in range(5):
    print(i)

0
1
2
3
4


In [31]:
list(range(5))

[0, 1, 2, 3, 4]

In [32]:
for i in [4, 7, "hello"]:
    print(i)

4
7
hello


In [34]:
x=7
while x > 2:
    print(x)
    x = x-1

7
6
5
4
3


In [35]:
x = 5
while True:
    print(x)
    x=x-1
    if x<=2:
        break

5
4
3


In [36]:
squares = []
for i in range(10):
    squares.append(i**2)
print(squares)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [38]:
[i**2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [39]:
[i**2 if i %2 ==0 else "hello"+str(i) for i in range(10)]

[0, 'hello1', 4, 'hello3', 16, 'hello5', 36, 'hello7', 64, 'hello9']

In [41]:
with open("some_file.txt") as my_file:
    lines = my_file.readlines()
lines

['This is a strange file.\n',
 'with some text\n',
 'and another line\n',
 '\n',
 'kjdkfdlnslknglksdnlgndlg']

In [45]:
[line.count("a") for line in lines]

[2, 0, 2, 0, 0]

## Functions

In [51]:
def my_function(x:int, y:float) -> float:
    a = x*y
    return a

my_function(3, 7.2)

21.6

In [52]:
%%timeit   #tells Jupyter to time the execution of the entire cell.
sum(x**2 for x in range(1000))

30.3 μs ± 208 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Numpy

In [1]:
import numpy as np

In [6]:
a = np.array([6.5, 7.2, 2, -4])
print(a)
b=np.arange(10)
print(b)
c = np.arange(4)
print(c)

[ 6.5  7.2  2.  -4. ]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]


In [12]:
a.mean()
a.max()
a.sum()
2*a + c
np.sin(a)

array([0.21511999, 0.79366786, 0.90929743, 0.7568025 ])